# Generated by Django 4.0.3 on 2022-06-22 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0038_studentgroups_registration'),
        ('authen', '0007_profiles_teacher'),
        ('students', '0005_alter_regions_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workless', models.BooleanField(default=False, verbose_name='Безработный')),
                ('oo_new', models.CharField(max_length=500, null=True, verbose_name='Организация не из списка')),
                ('type', models.CharField(default='Физическое лицо', max_length=50, verbose_name='Оплата')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='centre.studentgroups', verbose_name='Курс')),
                ('mo', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.mos', verbose_name='Муниципальное образование')),
                ('oo', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.oos', verbose_name='Организация')),
                ('position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='centre.positions', verbose_name='Должность')),
                ('position_cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='centre.positioncategories', verbose_name='Категория должности')),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profilecourseforms', to='authen.profiles', verbose_name='Обучающийся')),
                ('region', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='students.regions', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Анкета регистрации на мероприятие',
                'verbose_name_plural': 'Анкеты регистрации на мероприятия',
            },
        ),
    ]
