# Generated by Django 4.0.3 on 2022-06-22 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0038_studentgroups_registration'),
        ('authen', '0007_profiles_teacher'),
        ('students', '0006_eventsforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='group',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='centre.studentgroups', verbose_name='Учебная группа (для договора оферты)'),
        ),
        migrations.AlterField(
            model_name='eventsforms',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='centre.studentgroups', verbose_name='Учебная группа'),
        ),
        migrations.AlterField(
            model_name='eventsforms',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profileeventforms', to='authen.profiles', verbose_name='Обучающийся'),
        ),
        migrations.CreateModel(
            name='EventApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='centre.studentgroups', verbose_name='Учебная группа')),
                ('offer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.docs', verbose_name='Договор оферты')),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profileeventapps', to='authen.profiles', verbose_name='Обучающийся')),
            ],
        ),
    ]
