# Generated by Django 4.0.3 on 2022-06-22 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_docs_group_alter_eventsforms_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapps',
            name='event_url',
            field=models.URLField(default='https://coko38.ru', verbose_name='Ссылка на мероприятие'),
        ),
        migrations.AddField(
            model_name='eventapps',
            name='pay_doc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apppaydoc', to='students.docs', verbose_name='Документ об оплате'),
        ),
        migrations.AlterField(
            model_name='eventapps',
            name='offer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appofferdoc', to='students.docs', verbose_name='Договор оферты'),
        ),
    ]
