# Generated by Django 4.0.3 on 2022-06-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_profiles_teacher'),
        ('centre', '0038_studentgroups_registration'),
        ('students', '0008_eventapps_event_url_eventapps_pay_doc_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventApps',
            new_name='EventsApps',
        ),
    ]
