# Generated by Django 4.0.3 on 2022-06-23 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_eventsapps_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsapps',
            options={'verbose_name': 'Заявка на участие в мероприятии', 'verbose_name_plural': 'Заявки на участие в мероприятиях'},
        ),
        migrations.AddField(
            model_name='eventsapps',
            name='date_create',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата подачи заявки'),
        ),
    ]
