# Generated by Django 4.0.3 on 2022-06-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_statuses_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsforms',
            name='type',
            field=models.BooleanField(default=True, verbose_name='Оплата'),
        ),
    ]
