# Generated by Django 4.0.3 on 2022-06-24 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_eventsforms_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='group',
        ),
    ]
