# Generated by Django 4.0.3 on 2022-06-24 06:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_profiles_teacher'),
        ('centre', '0039_alter_oos_full_name'),
        ('students', '0015_remove_docs_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Категория получаемого образования')),
            ],
            options={
                'verbose_name': 'Категория получаемого образования',
                'verbose_name_plural': 'Категории получаемого образования',
            },
        ),
        migrations.CreateModel(
            name='EducationsLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Уровень образования')),
            ],
            options={
                'verbose_name': 'Уровень образования',
                'verbose_name_plural': 'Уровени образования',
            },
        ),
        migrations.RenameModel(
            old_name='EventsApps',
            new_name='Apps',
        ),
        migrations.CreateModel(
            name='CoursesForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workless', models.BooleanField(default=False, verbose_name='Безработный')),
                ('oo_new', models.CharField(max_length=500, null=True, verbose_name='Организация не из списка')),
                ('check_surname', models.CharField(default='', max_length=100, verbose_name='Фамилия в дипломе')),
                ('check_edu_serial', models.CharField(default='', max_length=30, verbose_name='Cерия документа об образовании')),
                ('check_edu_number', models.CharField(default='', max_length=30, verbose_name='Номер документа об образовании')),
                ('check_edu_date', models.DateField(default=datetime.datetime.now, verbose_name='Дата выдачи документа об образовании')),
                ('type', models.BooleanField(default=True, verbose_name='Оплата')),
                ('cert_mail', models.BooleanField(default=False, verbose_name='Получение удостоверения почтой')),
                ('address', models.TextField(default='', max_length=1000, verbose_name='Физический адрес доставки удостоверения')),
                ('change_surname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='changesurnamedoc', to='students.docs', verbose_name='Документ о смене фамилии')),
                ('edu_cat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.educationcats', verbose_name='Категория получаемого образования')),
                ('edu_doc', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='edudoc', to='students.docs', verbose_name='Документ об образовании')),
                ('edu_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='students.educationslevels', verbose_name='Уровень образования')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='centre.studentgroups', verbose_name='Учебная группа')),
                ('mo', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.mos', verbose_name='Муниципальное образование')),
                ('oo', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.oos', verbose_name='Организация')),
                ('position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='centre.positions', verbose_name='Должность')),
                ('position_cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='centre.positioncategories', verbose_name='Категория должности')),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profilecoursesforms', to='authen.profiles', verbose_name='Обучающийся')),
                ('region', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='students.regions', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Анкета регистрации на курс',
                'verbose_name_plural': 'Анкеты регистрации на курсы',
            },
        ),
    ]
