# Generated by Django 4.0.3 on 2022-06-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_educationcats_educationslevels_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationsLevels',
            new_name='EducationLevels',
        ),
    ]
