# Generated by Django 4.0.3 on 2022-06-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_rename_educationslevels_educationlevels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesforms',
            old_name='check_edu_date',
            new_name='edu_date',
        ),
        migrations.RenameField(
            model_name='coursesforms',
            old_name='check_edu_number',
            new_name='edu_number',
        ),
        migrations.RenameField(
            model_name='coursesforms',
            old_name='check_edu_serial',
            new_name='edu_serial',
        ),
    ]
