# Generated by Django 4.0.3 on 2022-06-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_rename_check_edu_date_coursesforms_edu_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesforms',
            name='change_surname',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changesurnamedoc', to='students.docs', verbose_name='Документ о смене фамилии'),
        ),
    ]
