# Generated by Django 4.0.3 on 2022-06-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_coursesforms_change_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesforms',
            name='edu_date',
            field=models.DateField(default=None, null=True, verbose_name='Дата выдачи документа об образовании'),
        ),
    ]
