# Generated by Django 4.0.3 on 2022-06-28 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0040_alter_oos_full_name'),
        ('students', '0020_alter_coursesforms_edu_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesforms',
            name='position',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.positions', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='coursesforms',
            name='position_cat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.positioncategories', verbose_name='Категория должности'),
        ),
        migrations.AlterField(
            model_name='eventsforms',
            name='position',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.positions', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='eventsforms',
            name='position_cat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.positioncategories', verbose_name='Категория должности'),
        ),
    ]
