# Generated by Django 4.0.3 on 2022-06-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_alter_coursesforms_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='check_diploma_info',
            field=models.BooleanField(default=False, verbose_name='Проверка информации о дипломе'),
        ),
    ]
