# Generated by Django 4.0.3 on 2022-06-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_apps_check_diploma_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='offer',
        ),
        migrations.AddField(
            model_name='apps',
            name='survey_url',
            field=models.URLField(default='https://docs.google.com/forms/d/e/1FAIpQLSeIdFOzzH8jDe64hlofqvAkE5639E1VLGQnP7aCKOKnjnAS8g/viewform', verbose_name='Ссылка на мероприятие'),
        ),
    ]
