# Generated by Django 4.0.3 on 2022-06-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_remove_apps_offer_apps_survey_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='event_url',
            field=models.URLField(default=None, verbose_name='Ссылка на мероприятие'),
        ),
    ]
