# Generated by Django 4.0.3 on 2022-07-01 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_alter_apps_event_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='event_url',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='survey_url',
        ),
    ]
