# Generated by Django 4.0.3 on 2022-07-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_remove_apps_event_url_remove_apps_survey_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='check_pay',
            field=models.BooleanField(default=False, verbose_name='Проверка оплаты'),
        ),
    ]
