# Generated by Django 4.0.3 on 2022-07-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_apps_check_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='check_survey',
            field=models.BooleanField(default=False, verbose_name='Проверка прохождения опроса'),
        ),
    ]
