# Generated by Django 4.0.3 on 2022-07-13 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_apps_check_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='certificate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appcertdoc', to='students.docs', verbose_name='Скан удостоверения'),
        ),
    ]
