# Generated by Django 4.0.3 on 2022-05-18 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='patronymic',
            field=models.CharField(default='', max_length=100, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='sex',
            field=models.BooleanField(default=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='snils',
            field=models.CharField(default='', max_length=15, verbose_name='СНИЛС'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='surname',
            field=models.CharField(default='', max_length=100, verbose_name='Фамилия'),
        ),
    ]
