# Generated by Django 4.0.3 on 2022-05-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_profiles_birthday_profiles_name_profiles_patronymic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
        ),
    ]
