# Generated by Django 4.0.3 on 2022-05-23 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_alter_profiles_phone_alter_profiles_snils'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='date_reg',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
    ]
