# Generated by Django 4.0.3 on 2022-05-24 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_profiles_date_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authen.states', verbose_name='Государство'),
        ),
    ]
