# Generated by Django 4.0.3 on 2022-05-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_profiles_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='teacher',
            field=models.BooleanField(default=False, verbose_name='Преподаватель'),
        ),
    ]
