# Generated by Django 4.0.3 on 2022-05-26 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название МО')),
            ],
            options={
                'verbose_name': 'Муниципальное образование',
                'verbose_name_plural': 'Муниципальные образования',
            },
        ),
        migrations.CreateModel(
            name='OoTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование типа ОО')),
            ],
            options={
                'verbose_name': 'Тип ОО',
                'verbose_name_plural': 'Типы ОО',
            },
        ),
        migrations.CreateModel(
            name='PositionCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория должности',
                'verbose_name_plural': 'Категории должности',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Oos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=150, verbose_name='Краткое название ОО')),
                ('full_name', models.CharField(max_length=300, verbose_name='Полное название ОО')),
                ('form', models.CharField(max_length=150, verbose_name='Форма ОО')),
                ('mo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='centre.mos', verbose_name='МО')),
                ('type_oo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='centre.ootypes', verbose_name='Тип ОО')),
            ],
            options={
                'verbose_name': 'Образовательная организация',
                'verbose_name_plural': 'Образовательные организации',
            },
        ),
    ]
