# Generated by Django 4.0.3 on 2022-05-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oos',
            name='form',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Форма ОО'),
        ),
        migrations.AlterField(
            model_name='oos',
            name='full_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Полное название ОО'),
        ),
        migrations.AlterField(
            model_name='oos',
            name='short_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Краткое название ОО'),
        ),
    ]
