# Generated by Django 4.0.3 on 2022-05-29 12:20

import centre.models
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0003_alter_mos_name_alter_ootypes_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Учебная часть', max_length=300, verbose_name='Структурное подразделение')),
                ('name', models.CharField(default='Название', max_length=500, unique=True, verbose_name='Наименование программы')),
                ('duration', models.PositiveIntegerField(verbose_name='Объем программы (часов)')),
                ('annotation', models.TextField(max_length=1500, verbose_name='Аннотация')),
                ('order_id', models.CharField(max_length=50, verbose_name='Номер приказа')),
                ('order_date', models.DateField(auto_now=True, verbose_name='Дата приказа')),
                ('order_file', models.FileField(upload_to=centre.models.get_path, verbose_name='Скан приказа')),
                ('price', models.PositiveIntegerField(default='100', verbose_name='Стоимость')),
                ('categories', models.ManyToManyField(to='centre.positioncategories', verbose_name='Категории слушателей')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='StSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Наименование', max_length=150, verbose_name='Наименование модуля (раздела)')),
                ('total_hours', models.PositiveIntegerField(verbose_name='Общее количество часов')),
                ('lecture_hours', models.PositiveIntegerField(verbose_name='Количество лекционных часов')),
                ('practice_hours', models.PositiveIntegerField(verbose_name='Количество часов практики')),
                ('individual_hours', models.PositiveIntegerField(verbose_name='Количество часов самостоятельной работы')),
                ('control_form', models.CharField(default='-', max_length=100, verbose_name='Форма контроля')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='centre.stschedule', verbose_name='Родитель')),
                ('program', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='centre.programs', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Раздел (модуль) КУГ',
                'verbose_name_plural': 'Разделы (модули) КУГ',
                'unique_together': {('program', 'name')},
            },
        ),
    ]
