# Generated by Django 4.0.3 on 2022-05-30 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0004_programs_stschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория слушателей',
                'verbose_name_plural': 'Категории слушателей',
            },
        ),
        migrations.AlterModelOptions(
            name='positioncategories',
            options={'verbose_name': 'Категория должностей', 'verbose_name_plural': 'Категории должностей'},
        ),
        migrations.AddField(
            model_name='positions',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='centre.positioncategories', verbose_name='Категория должности'),
        ),
    ]
