# Generated by Django 4.0.3 on 2022-05-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0005_audiencecategories_alter_positioncategories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название должности'),
        ),
        migrations.AlterUniqueTogether(
            name='positions',
            unique_together={('name', 'cat')},
        ),
    ]
