# Generated by Django 4.0.3 on 2022-05-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0006_alter_positions_name_alter_positions_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiencecategories',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='positioncategories',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название категории'),
        ),
    ]
