# Generated by Django 4.0.3 on 2022-05-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0008_alter_programs_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencecategories',
            name='test',
            field=models.CharField(default='', max_length=50, verbose_name='Тестовое'),
        ),
    ]
