# Generated by Django 4.0.3 on 2022-05-31 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0009_audiencecategories_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiencecategories',
            name='test',
        ),
    ]
