# Generated by Django 4.0.3 on 2022-05-31 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0010_remove_audiencecategories_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='order_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата приказа'),
        ),
    ]
