# Generated by Django 4.0.3 on 2022-06-01 08:14

import centre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0011_alter_programs_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='name',
            field=models.CharField(default='', max_length=500, unique=True, verbose_name='Наименование программы'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='order_file',
            field=models.FileField(max_length=1000, upload_to=centre.models.get_path, verbose_name='Скан приказа'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость'),
        ),
    ]
