# Generated by Django 4.0.3 on 2022-06-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0012_alter_programs_name_alter_programs_order_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stschedule',
            name='type',
            field=models.BooleanField(default=True, verbose_name='Тип'),
        ),
    ]
