# Generated by Django 4.0.3 on 2022-06-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0017_alter_stschedule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stschedule',
            name='type',
        ),
        migrations.AddField(
            model_name='stschedule',
            name='serial_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
