# Generated by Django 4.0.3 on 2022-06-03 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0020_remove_stschedule_on_edit_programs_kug_on_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='Наименование')),
                ('hours', models.PositiveIntegerField(default=0, verbose_name='Объем (количество часов)')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Дата начала проведения')),
                ('date_finish', models.DateField(auto_now_add=True, verbose_name='Дата окончания проведения')),
                ('students_number', models.PositiveIntegerField(blank=True, verbose_name='Плановое количество мест')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Дата начала обучения')),
                ('date_finish', models.DateField(auto_now_add=True, verbose_name='Дата окончания обучения')),
                ('program', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CourseDPP', to='centre.programs', verbose_name='ДПП')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
