# Generated by Django 4.0.3 on 2022-06-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0022_studentgroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='date_finish',
            field=models.DateField(auto_now=True, verbose_name='Дата окончания обучения'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_start',
            field=models.DateField(auto_now=True, verbose_name='Дата начала обучения'),
        ),
    ]
