# Generated by Django 4.0.3 on 2022-06-05 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0023_alter_courses_date_finish_alter_courses_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='date_finish',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата окончания обучения'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_start',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата начала обучения'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_finish',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата окончания проведения'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_start',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата начала проведения'),
        ),
    ]
