# Generated by Django 4.0.3 on 2022-06-05 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_profiles_teacher'),
        ('centre', '0024_alter_courses_date_finish_alter_courses_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroups',
            name='curator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curator', to='authen.profiles', verbose_name='Куратор'),
        ),
    ]
