# Generated by Django 4.0.3 on 2022-06-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0025_studentgroups_curator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='hours',
            new_name='duration',
        ),
    ]
