# Generated by Django 4.0.3 on 2022-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0026_rename_hours_events_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='department',
            field=models.CharField(default='Учебная часть', max_length=300, verbose_name='Структурное подразделение'),
        ),
    ]
