# Generated by Django 4.0.3 on 2022-06-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0027_events_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='students_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Плановое количество мест'),
        ),
    ]
