# Generated by Django 4.0.3 on 2022-06-12 15:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_profiles_teacher'),
        ('centre', '0028_alter_events_students_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_hours', models.PositiveIntegerField(verbose_name='Количество лекционных часов')),
                ('practice_hours', models.PositiveIntegerField(verbose_name='Количество часов практики')),
                ('individual_hours', models.PositiveIntegerField(verbose_name='Количество часов самостоятельной работы')),
                ('lesson_time_start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время начала занятия')),
                ('lesson_time_finish', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время окончания занятия')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centre.courses', verbose_name='Курс')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='centre.courselessons', verbose_name='Родитель')),
                ('stschedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.stschedule', verbose_name='Раздел/тема')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authen.profiles', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
    ]
