# Generated by Django 4.0.3 on 2022-06-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0030_remove_courselessons_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselessons',
            name='level',
        ),
        migrations.RemoveField(
            model_name='courselessons',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='courselessons',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='courselessons',
            name='tree_id',
        ),
    ]
