# Generated by Django 4.0.3 on 2022-06-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0031_remove_courselessons_level_remove_courselessons_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='categories',
            field=models.ManyToManyField(to='centre.audiencecategories', verbose_name='Категории слушателей'),
        ),
    ]
