# Generated by Django 4.0.3 on 2022-06-17 04:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_profiles_teacher'),
        ('centre', '0032_events_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselessons',
            options={'verbose_name': 'Занятие (курсы)', 'verbose_name_plural': 'Занятия (курсы)'},
        ),
        migrations.CreateModel(
            name='EventsLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(max_length=500, verbose_name='Тема')),
                ('lecture_hours', models.PositiveIntegerField(verbose_name='Количество лекционных часов')),
                ('practice_hours', models.PositiveIntegerField(verbose_name='Количество часов практики')),
                ('lesson_time_start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время начала занятия')),
                ('lesson_time_finish', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время окончания занятия')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centre.events', verbose_name='Мероприятие')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authen.profiles', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Занятие (мероприятия)',
                'verbose_name_plural': 'Занятия (мероприятия)',
            },
        ),
    ]
