# Generated by Django 4.0.3 on 2022-06-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0034_remove_courselessons_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип мероприятия (ИКУ)')),
            ],
            options={
                'verbose_name': 'Тип мероприятия',
                'verbose_name_plural': 'Типы мероприятий',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость'),
        ),
    ]
