# Generated by Django 4.0.3 on 2022-06-20 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0035_eventtypes_events_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='centre.eventtypes', verbose_name='Тип мероприятия'),
        ),
    ]
