# Generated by Django 4.0.3 on 2022-06-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0036_events_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='type_dpp',
            field=models.CharField(default='Повышение квалификации', max_length=100, verbose_name='Тип программы'),
        ),
    ]
