# Generated by Django 4.0.3 on 2022-06-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0037_programs_type_dpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroups',
            name='registration',
            field=models.BooleanField(default=True, verbose_name='Регистрация в группу'),
        ),
    ]
