# Generated by Django 4.0.3 on 2022-06-30 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0043_stgroupstatuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroups',
            name='approve_group',
        ),
        migrations.RemoveField(
            model_name='studentgroups',
            name='registration',
        ),
        migrations.AddField(
            model_name='studentgroups',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='centre.stgroupstatuses', verbose_name='Статус учебной группы'),
        ),
    ]
