# Generated by Django 4.0.3 on 2022-06-30 05:59

import centre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0044_remove_studentgroups_approve_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroups',
            name='offer',
            field=models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', max_length=1000, upload_to=centre.models.get_path_offer, verbose_name='Скан договора оферты'),
        ),
    ]
