# Generated by Django 4.0.3 on 2022-06-30 08:44

import centre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0045_studentgroups_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroups',
            name='offer',
            field=models.FileField(default=None, max_length=1000, upload_to=centre.models.get_path_offer, verbose_name='Скан договора оферты'),
        ),
    ]
