# Generated by Django 4.0.3 on 2022-07-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0046_alter_studentgroups_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroups',
            name='event_url',
            field=models.URLField(default=None, verbose_name='Ссылка на мероприятие'),
        ),
        migrations.AddField(
            model_name='studentgroups',
            name='survey_url',
            field=models.URLField(default='https://docs.google.com/forms/d/e/1FAIpQLSeIdFOzzH8jDe64hlofqvAkE5639E1VLGQnP7aCKOKnjnAS8g/viewform', verbose_name='Ссылка на мероприятие'),
        ),
    ]
