# Generated by Django 4.0.3 on 2022-07-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0047_studentgroups_event_url_studentgroups_survey_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroups',
            name='event_url',
            field=models.URLField(default='https://coko38.ru', verbose_name='Ссылка на мероприятие'),
        ),
    ]
