# Generated by Django 4.0.3 on 2022-07-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0048_alter_studentgroups_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroups',
            name='survey_show',
            field=models.BooleanField(default=False, verbose_name='Показ ссылки на опрос'),
        ),
    ]
