# Generated by Django 4.0.3 on 2022-07-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0049_studentgroups_survey_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stschedule',
            name='control_form',
            field=models.CharField(default='', max_length=100, verbose_name='Форма контроля'),
        ),
    ]
