# Generated by Django 4.0.3 on 2022-07-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0050_alter_stschedule_control_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='mos',
            name='tpl_name',
            field=models.CharField(max_length=10, null=True, verbose_name='Краткое название (для xlsx)'),
        ),
    ]
