# Generated by Django 4.0.3 on 2022-07-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0051_mos_tpl_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ootypes',
            name='tpl_name',
            field=models.CharField(max_length=10, null=True, verbose_name='Краткое название (для xlsx)'),
        ),
        migrations.AddField(
            model_name='positioncategories',
            name='tpl_name',
            field=models.CharField(max_length=10, null=True, verbose_name='Краткое название (для xlsx)'),
        ),
    ]
