# Generated by Django 4.0.3 on 2022-07-17 09:34

import centre.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0008_profiles_health'),
        ('centre', '0052_ootypes_tpl_name_positioncategories_tpl_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата запуска процесса')),
                ('date_finish', models.DateTimeField(default=None, null=True, verbose_name='Дата окончания процесса')),
                ('type_report', models.CharField(default='', max_length=50, verbose_name='Тип отчета')),
                ('report', models.FileField(upload_to=centre.models.upload_reports, verbose_name='Файл отчета')),
                ('admin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authen.profiles', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
