# Generated by Django 4.0.3 on 2022-07-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0053_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='report',
            field=models.FileField(default=None, null=True, upload_to='', verbose_name='Файл отчета'),
        ),
    ]
