# Generated by Django 4.0.3 on 2022-07-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0054_alter_reports_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroups',
            name='study_form',
            field=models.CharField(default='Без использования ДОТ', max_length=100, verbose_name='Форма обучения группы'),
        ),
    ]
