# Generated by Django 4.0.3 on 2022-07-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0055_studentgroups_study_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Наименование параметра')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Параметр планирования',
                'verbose_name_plural': 'Параметры планирования',
            },
        ),
    ]
