# Generated by Django 4.0.3 on 2022-07-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0056_planningparameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningparameters',
            name='name',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='Наименование параметра'),
        ),
    ]
