# Generated by Django 4.0.3 on 2022-07-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0057_alter_planningparameters_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningparameters',
            name='alias',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Алиас'),
        ),
    ]
