# Generated by Django 4.0.3 on 2022-07-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0058_planningparameters_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselessons',
            name='trainee_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество часов стажировок'),
            preserve_default=False,
        ),
    ]
