# Generated by Django 4.0.3 on 2022-07-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0059_courselessons_trainee_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='stschedule',
            name='trainee_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество часов стажировок'),
            preserve_default=False,
        ),
    ]
