# Generated by Django 4.0.3 on 2022-07-20 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0060_stschedule_trainee_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselessons',
            name='distance',
            field=models.BooleanField(default=False, verbose_name='Дистанционное занятие'),
        ),
        migrations.AlterField(
            model_name='courselessons',
            name='lesson_time_finish',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Время окончания занятия'),
        ),
        migrations.AlterField(
            model_name='courselessons',
            name='lesson_time_start',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Время начала занятия'),
        ),
        migrations.AlterField(
            model_name='events',
            name='department',
            field=models.CharField(default='Учебный центр', max_length=300, verbose_name='Структурное подразделение'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='department',
            field=models.CharField(default='Учебный центр', max_length=300, verbose_name='Структурное подразделение'),
        ),
    ]
