# Generated by Django 4.0.3 on 2022-07-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0065_alter_programs_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='positions',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='positions',
            name='cat',
        ),
    ]
