# Generated by Django 4.0.3 on 2022-07-25 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0008_profiles_health'),
        ('centre', '0066_alter_positions_unique_together_remove_positions_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsCerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(default='', max_length=50, unique=True, verbose_name='Порядковый регистрационный номер')),
                ('blank_serial', models.CharField(default='', max_length=50, verbose_name='Серия бланка удостоверения')),
                ('blank_number', models.CharField(default='', max_length=50, verbose_name='Номер бланка удостоверения')),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.studentgroups', verbose_name='Учебная группа')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='authen.profiles', verbose_name='Обучающийся')),
            ],
            options={
                'verbose_name': 'Удостоверение о ПК',
                'verbose_name_plural': 'Удостоверения о ПК',
                'unique_together': {('blank_serial', 'blank_number')},
            },
        ),
    ]
