# Generated by Django 4.0.3 on 2022-07-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0067_studentscerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscerts',
            name='reg_number',
            field=models.CharField(default='', max_length=50, verbose_name='Порядковый регистрационный номер'),
        ),
    ]
