# Generated by Django 4.0.3 on 2022-07-25 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0068_alter_studentscerts_reg_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentscerts',
            unique_together={('reg_number', 'blank_serial', 'blank_number')},
        ),
    ]
