# Generated by Django 4.0.3 on 2022-07-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0070_courses_place_events_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroups',
            name='date_enroll',
            field=models.DateField(default=None, null=True, verbose_name='Дата приказа о зачислении'),
        ),
        migrations.AddField(
            model_name='studentgroups',
            name='date_exp',
            field=models.DateField(default=None, null=True, verbose_name='Дата приказа об отчислении'),
        ),
        migrations.AddField(
            model_name='studentgroups',
            name='enroll_number',
            field=models.CharField(default='', max_length=50, verbose_name='Номер приказа о зачислении'),
        ),
        migrations.AddField(
            model_name='studentgroups',
            name='exp_number',
            field=models.CharField(default='', max_length=50, verbose_name='Номер приказа об отчислении'),
        ),
        migrations.AlterField(
            model_name='studentgroups',
            name='survey_url',
            field=models.URLField(default='https://docs.google.com/forms/d/e/1FAIpQLSeIdFOzzH8jDe64hlofqvAkE5639E1VLGQnP7aCKOKnjnAS8g/viewform', verbose_name='Ссылка на опрос'),
        ),
    ]
