# Generated by Django 4.0.3 on 2022-07-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0071_studentgroups_date_enroll_studentgroups_date_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='order_date',
            field=models.DateField(default=None, null=True, verbose_name='Дата приказа'),
        ),
    ]
