# Generated by Django 4.0.3 on 2022-07-27 06:30

import centre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0072_alter_programs_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='order_file',
            field=models.FileField(max_length=1000, null=True, upload_to=centre.models.get_path, verbose_name='Скан приказа'),
        ),
    ]
